# Generated by Django 2.0.2 on 2018-04-18 22:02

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='farm',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='farm',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='farm',
            name='acres',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='main_crop',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='farm',
            name='owned_since',
            field=models.IntegerField(blank=True, choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018),
        ),
        migrations.AlterField(
            model_name='farm',
            name='ownership_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
